---
title: "Tratando IF Data Bacen"
author: "Juan Doudement"
date: "2025-11-04"
output: html_document
---

```{r include=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(janitor)
library(tidyr)
```

# Abrindo os data frames que estão no workspace
```{r include=FALSE}
load("Juan_Trabalho.RData")
```

```{r}
save.image("Juan_Trabalho.RData")
```

# Tratando o df passivo para encontrar o patrimonio líquido
```{r message=TRUE}
Patrimônio_Líquido <- bind_rows(Passivo)  %>%
  filter(TCB == "b1", Código %in% AT_6$Código) %>%
  dplyr::select(Instituição, Código, Data, `Patrimônio.Líquido..j.`) %>%
  rename(Patrimônio_Líquido = `Patrimônio.Líquido..j.`)
  Patrimônio_Líquido <- na.omit(Patrimônio_Líquido)
```


```{r echo=TRUE}
head(Passivo$`03_2020_Passivo.csv`,5)
```


```{r}
Passivo_06.2020 <- Passivo$`06_2000_Passivo.csv` %>%
  dplyr::select(
    Data,
    Instituição,
    Patrimônio.Líquido..j.)
```


```{r echo=TRUE}
head(Passivo_06.2020,10)
```
# Tratando faltantes para PL
* Tive que refazer por que estava sem valores para alguns anos devido ao no da coluna 
```{r eval=FALSE, include=FALSE}
Bancos_FALTANTES_06_2020 <- Passivo$`03_2000_Passivo.csv` %>%
  filter(TCB == "b1",
         Código %in% AT_6$Código,
         Data %in% FALTANTES_BB) %>%
  dplyr::select(Instituição, Código, Data, Patrimônio.Líquido..i.,Patrimônio.Líquido..j.) %>%
  rename(Patrimônio_Líquido = C(Patrimônio.Líquido..i.,Patrimônio.Líquido..j.))
```


```{r echo=FALSE}
head(Ativo_Total,25)
```

```{r}
head(ROE_BB,20)
```


